# Generated by Django 4.1.7 on 2023-04-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
