# Generated by Django 4.1.7 on 2023-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0002_rename_employees_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.TextField(choices=[])),
                ('price', models.IntegerField()),
            ],
        ),
    ]
