# Generated by Django 4.1.7 on 2023-04-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0003_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
