# Generated by Django 4.1.7 on 2023-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0006_customers_itemtype_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
