# Generated by Django 4.1.7 on 2023-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0008_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
