# Generated by Django 4.1.7 on 2023-04-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0010_customers_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
