# Generated by Django 4.1.7 on 2023-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0012_matlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='pay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
