# Generated by Django 4.2 on 2023-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0013_attendance_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('pay', models.IntegerField()),
            ],
        ),
    ]
