# Generated by Django 4.2 on 2023-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0014_etransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='advance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
