# Generated by Django 4.2 on 2023-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0016_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
