# Generated by Django 4.2 on 2023-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricapp', '0019_matlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('pay', models.IntegerField()),
            ],
        ),
    ]
